version: "3.0"
services:
  frontend:
    build: ./client
    image: frontend:latest
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
  backend:
    build: ./server
    image: backend:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - data:/data/db
      - ./mongosetup.js:/docker-entrypoint-initdb.d/mongosetup.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: pokemon
    expose:
      - 27017
    restart: always

volumes:
  data:
  .:
